version: "3.8"
services:
  eof2025_db:
    image: "postgres:14"
    container_name: "eof2025_db"
    ports:
      - "5432:5432"
#    volumes:
#      - /database:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eof2025_db
  tg_bot:
    build: ./
    container_name: "eof2025_bot"
    restart: always
    env_file:
      - .env