version: "3.8"
services:
#  eof2025_db:
#    image: "postgres:14"
#    container_name: "eof2025_db"
#    ports:
#      - "5432:5432"
#    volumes:
#      - /database:/var/lib/postgresql/data
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: eof2025_db
  redis:
    image: redis
    container_name: "redis"
    restart: always
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_USER=default
      - REDIS_USER_PASSWORD=redis
    volumes:
      - ./redis:/data
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    ports:
      - "6379:6379"
  tg_bot:
    build: ./
    container_name: "eof2025_bot"
    restart: always
    volumes:
      - .dev.env:/eof2025_bot/.dev.env
      - .env:/eof2025_bot/.env
      - ./bot_config.py:/eof2025_bot/bot_config.py
    depends_on:
      - redis